apiVersion: v1
kind: ConfigMap
metadata:
  name: laravelteszt-config
data:
  # property-like keys; each key maps to a simple value
  APP_NAME: "Laravel Teszt App"
  APP_ENV: "local"
  DB_HOST: "laravelteszt-database"
  DB_PORT: "3306"
  DB_DATABASE: "laravelteszt-database"
  DB_USERNAME: "laravelteszt"
  DB_PASSWORD: "laravelteszt"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: laravelteszt-database-config
data:
  # property-like keys; each key maps to a simple value
  MYSQL_ROOT_PASSWORD: "admin"
  MYSQL_DATABASE: "laravelteszt"
  MYSQL_USER: "laravelteszt"
  MYSQL_PASSWORD: "laravelteszt"
---
apiVersion: v1
kind: Pod
metadata:
  name: laravelteszt-pod
spec:
  containers:
    - name: laravelteszt-app
      image: 'varhegyisz/laraveltest:latest'
      ports:
        - containerPort: 80
      envFrom:
        - configMapRef:
            name: laravelteszt-config
    - name: laravelteszt-db
      image: 'mariadb:latest'
      envFrom:
        - configMapRef:
            name: laravelteszt-database-config
---
kind: Service
apiVersion: v1
metadata:
  name: laravelteszt
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30000
  selector:
    name: laravelteszt-app